### ISSUE TITLE
Sarabun font with <strong> tag does not work

### ISSUE THREAD

**Issue by pladaak** [SeedWebs/seed#6]
See https://seed.seeddemo.com/บทความเรื่องชา/ for example,

`<strong>ชา</strong>` see no difference from the rest normal size. 

seed v2.0.9 has its own test page here, http://u1256.todsorb.org/ฟอนต์-sarabun/.

**Comment by MennStudio** [comment]
Thank you so much.

I tried with files in member page https://th.seedthemes.com/account/ and found no problem.

This repo is not include font files. Can you try download from member page instead?

<img width="798" alt="Screenshot 2020-06-10 17 52 51" src="https://user-images.githubusercontent.com/4017086/84259868-4c54b600-ab43-11ea-9942-a74524e5d6b3.png">

**Comment by pladaak** [comment]
Ops! my bad, Chrome 83 and Safari 13 seems no problem, but Firefox 77 (on the left).  

<img width="512" alt="ff77-chm83-sfr13" src="https://user-images.githubusercontent.com/66716878/84261587-33013900-ab46-11ea-9264-9e9587feafaa.png">

**Comment by MennStudio** [comment]
Umm, I'll check it krub.

**Comment by pladaak** [comment]
I fixed this issue by  patching  "_fonts.scss" as follow,

`@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-Light.woff2') format('woff2'),
         url('../fonts/Sarabun-Light.woff') format('woff'),
         url('../fonts/Sarabun-Light.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
    font-display: fallback;
}
@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-LightItalic.woff2') format('woff2'),
         url('../fonts/Sarabun-LightItalic.woff') format('woff'),
         url('../fonts/Sarabun-LightItalic.ttf') format('truetype');
    font-weight: 300;
    font-style: italic;
    font-display: fallback;
}

@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-Regular.woff2') format('woff2'),
         url('../fonts/Sarabun-Regular.woff') format('woff'),
         url('../fonts/Sarabun-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
    font-display: fallback;
}
@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-Italic.woff2') format('woff2'),
         url('../fonts/Sarabun-Italic.woff') format('woff'),
         url('../fonts/Sarabun-Italic.ttf') format('truetype');
    font-weight: 400;
    font-style: italic;
    font-display: fallback;
}

@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-Medium.woff2') format('woff2'),
         url('../fonts/Sarabun-Medium.woff') format('woff'),
         url('../fonts/Sarabun-Medium.ttf') format('truetype');
    font-weight: 500;
    font-style: normal;
    font-display: fallback;
}
@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-MediumItalic.woff2') format('woff2'),
         url('../fonts/Sarabun-MediumItalic.woff') format('woff'),
         url('../fonts/Sarabun-MediumItalic.ttf') format('truetype');
    font-weight: 500;
    font-style: italic;
    font-display: fallback;
}

@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-SemiBold.woff2') format('woff2'),
         url('../fonts/Sarabun-SemiBold.woff') format('woff'),
         url('../fonts/Sarabun-SemiBold.ttf') format('truetype');
    font-weight: 600;
    font-style: normal;
    font-display: fallback;
}
@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-SemiBoldItalic.woff2') format('woff2'),
         url('../fonts/Sarabun-SemiBoldItalic.woff') format('woff'),
         url('../fonts/Sarabun-SemiBoldItalic.ttf') format('truetype');
    font-weight: 600;
    font-style: italic;
    font-display: fallback;
}

@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-Bold.woff2') format('woff2'),
         url('../fonts/Sarabun-Bold.woff') format('woff'),
         url('../fonts/Sarabun-Bold.ttf') format('truetype');
    font-weight: 700;
    font-style: normal;
    font-display: fallback;
}
@font-face {
    font-family: 'Sarabun';
    src: url('../fonts/Sarabun-BoldItalic.woff2') format('woff2'),
         url('../fonts/Sarabun-BoldItalic.woff') format('woff'),
         url('../fonts/Sarabun-BoldItalic.ttf') format('truetype');
    font-weight: 700;
    font-style: italic;
    font-display: fallback;
}
`

and using all the font files from 
[https://github.com/cadsondemak/Sarabun/tree/master/fonts](https://github.com/cadsondemak/Sarabun/tree/master/fonts)

**Comment by MennStudio** [comment]
โอ้ ขอบคุณมากเลยครับ

**Comment by pladaak** [comment]
I reproduced this page [http://u1256.todsorb.org/ฟอนต์-sarabun/](http://u1256.todsorb.org/ฟอนต์-sarabun/) with the latest version. Is this issue still present only Firefox? (Firefox 88.0.1 64-bit on macOS 11.3.1)

**Comment by MennStudio** [comment]
Sorry for this long-time bug. I can't reproduce it.

But now, I re-download and put on latest submit on github.

Hope this helps.


<img width="1278" alt="CleanShot 2021-05-28 at 08 28 39@2x" src="https://user-images.githubusercontent.com/4017086/119916463-c8335280-bf8e-11eb-8d50-6b91cb49c40d.png">

**Comment by pladaak** [comment]
Re-installed but the bug still there on my macOS. (No bug on Firefox + Window)
What I suspect is this line https://github.com/SeedWebs/seed/blob/5230a2b4ea4bb49c57884b32d3dab0d38567b8b1/css/scss/_begin.scss#L67

and those of the font define 
https://github.com/SeedWebs/seed/blob/5230a2b4ea4bb49c57884b32d3dab0d38567b8b1/css/scss/_fonts.scss#L26-L49

or nothing, just my fault :)
