### ISSUE TITLE
Headline subtitle has wrong closing tag

### ISSUE THREAD

**Issue by pladaak** [SeedWebs/seed#9]
Please see this line on the content headline template,
https://github.com/SeedWebs/seed/blob/master/template-parts/content-headline.php#L50

**Comment by mennwebs** [comment]
Thanks so much krub.

fixed with commit [7a05bd6](https://github.com/SeedWebs/seed/commit/7a05bd6a5fcd28c41f508139f8278d185a7c08bf)
